from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .models import MemoryRecord


class MemoryRepository(Protocol):
    available: bool

    def upsert(self, record: MemoryRecord) -> MemoryRecord | None: ...
    def list(self, *, category: str | None = None, kind: str | None = None) -> list[MemoryRecord]: ...
    def lookup(self, query: str | None, *, limit: int, max_chars: int) -> list[MemoryRecord]: ...
    def delete(self, memory_id: str) -> bool: ...
    def delete_expired(self, now: datetime) -> int: ...
    def cleanup_candidates(self, now: datetime, *, stale_before: datetime, min_strength: float) -> list[MemoryRecord]: ...
