from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .models import Habit, HabitObservation


class HabitRepository(Protocol):
    available: bool

    def add_observation(self, observation: HabitObservation) -> HabitObservation | None: ...
    def list_observations(self) -> list[HabitObservation]: ...
    def upsert_habit(self, habit: Habit) -> Habit | None: ...
    def list_habits(self) -> list[Habit]: ...
    def delete_observations_before(self, cutoff: datetime) -> int: ...
    def compact_observations(self, *, max_per_pattern: int) -> int: ...
    def delete_habit(self, habit_id: str) -> bool: ...
